blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .feeds import LatestBlogFeed

app_name = 'blog'

urlpatterns = [

    # Registration
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # change password urls
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # reset password urls
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('feed/', LatestBlogFeed(), name='post_feed'),
    path('<slug:type_news>/', views.home, name='home_tag_type'),
    path('share/<int:post_id>/', views.post_share, name='share_post'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.detail, name='detail'),

]

configurate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import BlogSiteMap

sitemaps = {
    'Posts': BlogSiteMap
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings


class BlogManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Blog(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique=True, blank=True, null=False)
    image = models.ImageField(upload_to='media/')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='blog')
    object = models.Manager()
    published = BlogManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.created.year,
                                            self.created.month,
                                            self.created.day,
                                            self.slug])

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):  # new
    #     self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    post = models.ForeignKey(Blog,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField('Имя', max_length=100)
    email = models.EmailField("Емаил")
    body = models.TextField('Описание')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Комментарий статьи : {}...  от пользователя {}".format(self.post, self.post.user)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Профиль для пользователя {}'.format(self.user.username)

# class Post(models.Model):
#     title = models.CharField(max_length=250)
#     slug = models.SlugField(max_length=250,unique_for_date='publish')
#     author = models.ForeignKey(User,on_delete=models.CASCADE,
#                                related_name='blog_posts')
#     body = models.TextField()
#     publish = models.DateTimeField(default=timezone.now)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=10, choices=STATUS_CHOICES,
#                               default='draft')

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from blog.models import Comment


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.PasswordInput)

    class Meta:
        model = User

        fields = ('username', 'first_name', 'email')


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('упс пароли не совпадают.')
        return cd['password2']


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    you_email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.core.mail import send_mail
from taggit.models import Tag
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Blog, Comment
from .forms import EmailPostForm, CommentForm, UserRegistrationForm


def post_share(request, post_id):
    post = get_object_or_404(Blog, id=post_id, active=True)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}'.format(post.title[:30])
            message = f'сообщение от -  {cd["name"]}  : {cd["comments"]}\n\n' \
                      f'Email отправителя  -  {cd["you_email"]}\n\n' \
                      f'Узнать подробнее по ссылке : {post_url}'
            to = '{}'.format(cd['to'])
            send_mail(subject, message, 'vinogradovpavel32@gmail.com', [to])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent,
    }
    return render(request, 'blog/post_share.html', context)


@login_required
def home(request, type_news=None):
    # Views home page
    object_list = Blog.published.all()
    tag = None
    if type_news:
        tag = get_object_or_404(Tag, slug=type_news)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')

    # Pagination home page
    try:
        blog = paginator.page(page)
    except EmptyPage:
        blog = paginator.page(1)
    except PageNotAnInteger:
        blog = paginator.page(paginator.num_pages)

    context = {
        'blog': blog,
        'page': page,
        'tag': tag,
        'comments': object_list,
    }
    return render(request, 'blog/home.html', context)


def detail(request, year, month, day, slug):
    post = get_object_or_404(Blog, slug=slug,
                             created__year=year,
                             created__month=month,
                             created__day=day, )
    new_comment = None
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
        'new_comment': new_comment,
    }
    return render(request, 'blog/details.html', context)


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()
            context = {'new_user': new_user}
            return render(request, 'blog/register_done.html', context)
    else:
        user_form = UserRegistrationForm()
    context = {'user_form': user_form}
    return render(request, 'blog/register.html', context)

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}

{% block content %}


{% endblock %}

blog/templates/blog/details.html
{% extends 'base.html' %}
{% block title %}{{ post.title|truncatewords:5 }}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mb-4">
        <div class="card mb-3 text-center mt-2">
            <img src="{{ post.image.url }}" class="card-img-top img_size img-thumbnail" alt="{{ post.title|truncatewords:10 }}">
            <div class="card-body">
                <h5 class="card-title">{{ post.title|title }}</h5>
                <p class="card-text">{{ post.body|linebreaks }}</p>
                <p class="card-text"><small class="text-muted">Автор: {{ post.user|title }}</small></p>
                <p class="card-text"><small class="text-muted">Опубликованно: {{ post.created }}</small></p>
            </div>
        </div>
        <a href="{% url 'blog:home' %}" class="btn btn-outline-success">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                 class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                <path fill-rule="evenodd"
                      d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
            </svg>
            Назад</a>
        <a href="{% url 'blog:share_post' post.id %}" class="btn btn-outline-success">Поделиться
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send-fill"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89.471-1.178-1.178.471L5.93 9.363l.338.215a.5.5 0 0 1 .154.154l.215.338 7.494-7.494Z"/>
            </svg>
        </a>
        <br>
        <div class="text-center">
            {% if comments.count != 0 %}
                <span class="mb-4">Коментаниев у статьи: </span>{{ comments.count }}
                {% for comment in comments %}
                    <div>
                       <p class="bg-danger text-white d-inline-flex">
                        {{ comment.post.user}}:
                       </p>
                        {{ comment.body }}
                    </div>
                    <br>
                {% endfor %}
            {% else %}
                <span>У статьи нет коментариев</span>
            {% endif %}
            {% if new_comment %}
                <h2>Ваш комментарий успешно добавлен.</h2>
                <a href="{{ post.get_absolute_url }}">Хотите добавить коментарий</a>
            {% else %}
                <div class="">
                    <form class="col-7 text-left" action="" method="POST">
                        {% csrf_token %}
                        {{ comment_form|crispy }}
                        <button type="submit" class="btn btn-primary mt-1"> Отправить коментарий</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block title %}Home{% endblock %}

{% block content %}
    <div class="container mt-4 d-flex">
        <div class="row row-cols-1 row-cols-md-3 g-2">
            {% for i in blog %}
                <div class="col  col_card">
                    <a href="{{ i.get_absolute_url }}">
                        <div class="card">
                            <img src="{{ i.image.url }}" class="card-img-top" alt="{{ i.title|truncatewords:10 }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ i.title }}</h5>
                                <p class="card-text">{{ i.body|truncatewords:20 }}</p>
                            </div>
                            <p class="tags">
                                Категория:
                                {% for tag in i.tags.all %}
                                    <a href="{% url "blog:home_tag_type" tag.slug %}">
                                        {{ tag.name }}</a>
                                    {% if not tag %}
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="row w-auto another_blog">
            <h4>Всего Статьей : {% total_post %}</h4>
            <p>
                <a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a>
            </p>
            <hr>
            <p5>Последние статьи:</p5>
            {% show_latest 3 %}
        </div>
    </div>
    <div class="container">
        {% include 'blog/components/pagination.html' with page=blog %}
    </div>

{% endblock %}

blog/templates/blog/post_share.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Post Share{% endblock %}
{% block content %}
    <div class="container d-flex mt-3">
        {% if sent %}
            <div class="col-5">
                <h1>E-mail Успешно отправлен</h1>
                <a href="{% url 'blog:home' %}" class="btn btn-outline-warning">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                        <path fill-rule="evenodd"
                              d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                    </svg>
                    Назад</a>
            </div>

        {% else %}
            <div class="col-5">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mt-2">
                        <button type="submit" class="btn btn-outline-success">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-cursor"
                                 viewBox="0 0 16 16">
                                <path d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103zM2.25 8.184l3.897 1.67a.5.5 0 0 1 .262.263l1.67 3.897L12.743 3.52 2.25 8.184z"/>
                            </svg>
                            Отправить
                        </button>
                        <a href="{% url 'blog:home' %}" class="btn btn-outline-warning">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                      d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                                <path fill-rule="evenodd"
                                      d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                            Назад</a>
                    </div>
                </form>
            </div>
        {% endif %}
        <div class="card text-center col margin_left">
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.title|truncatewords:5 }}">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.body }}</p>
                {#                <a href="#" class="btn btn-primary"></a>#}
            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Создай аккаунт{% endblock %}
{% block content %}
    <div class="container mt-4">
        <div class="row col-5">
            <h1>Регистрация</h1>
            <p>Пожалуйста, зарегистрируйтесь, используя следующую форму:</p>
            <form method="post">
                {{ user_form|crispy }}
                {% csrf_token %}
                <p class="mt-3"><input type="submit" class="btn btn-outline-success" value="Создай мой аккаунт"></p>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog/register_done.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
    <div class="container mt-4">
        <h1>Добро пожаловать! {{ new_user.first_name }}!</h1>
        <p>Ваша учетная запись успешно создана. Теперь вы можете
            <a href="{% url "blog:login" %}">войти</a>.
        </p>
    </div>
{% endblock %}