blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .feeds import LatestBlogFeed

app_name = 'blog'

urlpatterns = [

    # Registration
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # change password urls
    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # reset password urls
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('feed/', LatestBlogFeed(), name='post_feed'),
    path('<slug:type_news>/', views.home, name='home_tag_type'),
    path('share/<int:post_id>/', views.post_share, name='share_post'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.detail, name='detail'),

]

configurate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import BlogSiteMap

sitemaps = {
    'Posts': BlogSiteMap
}

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings


class BlogManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Blog(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique=True, blank=True, null=False)
    image = models.ImageField(upload_to='media/')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='blog')
    object = models.Manager()
    published = BlogManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.created.year,
                                            self.created.month,
                                            self.created.day,
                                            self.slug])

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):  # new
    #     self.slug = slugify(self.title)
    #     super().save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    post = models.ForeignKey(Blog,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField('Имя', max_length=100)
    email = models.EmailField("Емаил")
    body = models.TextField('Описание')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Комментарий статьи : {}...  от пользователя {}".format(self.post, self.post.user)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Профиль для пользователя {}'.format(self.user.username)

# class Post(models.Model):
#     title = models.CharField(max_length=250)
#     slug = models.SlugField(max_length=250,unique_for_date='publish')
#     author = models.ForeignKey(User,on_delete=models.CASCADE,
#                                related_name='blog_posts')
#     body = models.TextField()
#     publish = models.DateTimeField(default=timezone.now)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=10, choices=STATUS_CHOICES,
#                               default='draft')

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from blog.models import Comment


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.PasswordInput)

    class Meta:
        model = User

        fields = ('username', 'first_name', 'email')


    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('упс пароли не совпадают.')
        return cd['password2']


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30)
    you_email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.core.mail import send_mail
from taggit.models import Tag
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Blog, Comment
from .forms import EmailPostForm, CommentForm, UserRegistrationForm


def post_share(request, post_id):
    post = get_object_or_404(Blog, id=post_id, active=True)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}'.format(post.title[:30])
            message = f'сообщение от -  {cd["name"]}  : {cd["comments"]}\n\n' \
                      f'Email отправителя  -  {cd["you_email"]}\n\n' \
                      f'Узнать подробнее по ссылке : {post_url}'
            to = '{}'.format(cd['to'])
            send_mail(subject, message, 'vinogradovpavel32@gmail.com', [to])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent,
    }
    return render(request, 'blog/post_share.html', context)


@login_required
def home(request, type_news=None):
    # Views home page
    object_list = Blog.published.all()
    tag = None
    if type_news:
        tag = get_object_or_404(Tag, slug=type_news)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')

    # Pagination home page
    try:
        blog = paginator.page(page)
    except EmptyPage:
        blog = paginator.page(1)
    except PageNotAnInteger:
        blog = paginator.page(paginator.num_pages)

    context = {
        'blog': blog,
        'page': page,
        'tag': tag,
        'comments': object_list,
    }
    return render(request, 'blog/home.html', context)


def detail(request, year, month, day, slug):
    post = get_object_or_404(Blog, slug=slug,
                             created__year=year,
                             created__month=month,
                             created__day=day, )
    new_comment = None
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
        'new_comment': new_comment,
    }
    return render(request, 'blog/details.html', context)


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()
            context = {'new_user': new_user}
            return render(request, 'blog/register_done.html', context)
    else:
        user_form = UserRegistrationForm()
    context = {'user_form': user_form}
    return render(request, 'blog/register.html', context)

blog/templates/blog/components/latest_post.html
<ul>
    {% for i in latest_posts %}
    <li>
        <a href="{{ i.get_absolute_url }}">{{ i.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Create Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">About author</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-warning" type="submit">Search</button>
            </form>
            <div class="user">
                 <span >
                     {% if request.user.is_authenticated %}
                         Привет {{ request.user.first_name|title }}
                         <a href="{% url "blog:logout" %}">Выйти </a>
                     {% else %}
                         <a href="{% url "blog:login" %}">Войти </a>
                     {% endif %}
                 </span>
            </div>
        </div>
    </div>
</nav>

blog/templates/blog/components/pagination.html
<div class="pagination">
 <span class="step-links">
 {% if page.has_previous %}
     <a href="?page={{ page.previous_page_number }}">
           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                <path fill-rule="evenodd"
                      d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
            </svg>
         Назад</a>
 {% endif %}
     <span class="current">
 Страница {{ page.number }} из {{ page.paginator.num_pages }}.
 </span>
     {% if  page.has_next %}
         <a href="?page={{ page.next_page_number }}">Вперед
         <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
              class="bi bi-chevron-double-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd"
        d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
  <path fill-rule="evenodd"
        d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
</svg>
         </a>
     {% endif %}
 </span>
</div>